version: "3.1"
services:
  python:
    environment:
      - PYTHONUNBUFFERED=1
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application_container
    volumes:
      - ./:/app

  arangodb:
    image: arangodb:3.11.3
    container_name: database_container
    ports:
       - 8000:8529
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./arangodb:/var/lib/arangodb3

  nginx:
    image: nginx:latest
    container_name: reverse_proxy_container
    ports:
      - 4000:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - python

